@host = http://localhost:8080
@token = igxApoxPwT66sYBzenkEUf6YMtzk8Zh7

POST {{host}}/auth/login
Auth-token: {{token}}
Content-Type: application/json

{
  "email": "email",
  "password": "password"
}