@host = http://localhost:8080
@token = igxApoxPwT66sYBzenkEUf6YMtzk8Zh7
@course_id = 1

### Create
POST {{host}}/course
Auth-token: {{token}}
Content-Type: application/json

{
  "title": "Python 101",
  "description": "Intro course",
  "duration_seconds": 5400,
  "format": "video",
  "course_type": "self_paced",
  "thumbnail_url": "https://example.com/thumb.png",
  "download_url": "https://example.com/course.zip",
  "tags": [
    "python",
    "intro"
  ]
}

### List
GET {{host}}/course
Auth-token: {{token}}

### Detail (composed DTO)
GET {{host}}/course/{{course_id}}
Auth-token: {{token}}

### Upload course
POST {{host}}/course/{{course_id}}/upload
Auth-token: {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="sample_1920x1080.mp4"
Content-Type: video/mp4

< ../samples/sample_1920x1080.mp4
--MyBoundary--

### Download
GET {{host}}/course/{{course_id}}/download
Auth-token: {{token}}

### Progress (get)
GET {{host}}/course/{{course_id}}/progress
Auth-token: {{token}}

### Progress (update)
PATCH {{host}}/course/{{course_id}}/progress
Auth-token: {{token}}
Content-Type: application/json

{
  "progress": 0
}

### Progress (complete)
PATCH {{host}}/course/{{course_id}}/progress
Auth-token: {{token}}
Content-Type: application/json

{
  "progress": 100
}
