@host = http://localhost:8080
@token = igxApoxPwT66sYBzenkEUf6YMtzk8Zh7

### Create
POST {{host}}/user/create
Auth-token: {{token}}
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "securepassword123",
  "phone": "+123456789",
  "website": "https://johndoe.dev",
  "bio": "Entrepreneur.",
  "gender": "male"
}

### Edit (partial)
PATCH {{host}}/user/edit/1
Auth-token: {{token}}
Content-Type: application/json

{
  "name": "John D.",
  "email": "john.d@example.com",
  "bio": "Builder.",
  "active": true
}

### Get
GET {{host}}/user/get/1
Auth-token: {{token}}
Content-Type: application/json